namespace CardioLeaf
{
    partial class ChartControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea2 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea3 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea4 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea5 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea6 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea7 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea8 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea9 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea10 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea11 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea12 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series2 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series3 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series4 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series5 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series6 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series7 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series8 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series9 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series10 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series11 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series12 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series13 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series14 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series15 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series16 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series17 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series18 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series19 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series20 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series21 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series22 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series23 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series24 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ChartControl));
            this.modularChart = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.userMarker = new System.Windows.Forms.PictureBox();
            this.flag = new System.Windows.Forms.PictureBox();
            this.scaleLabel = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.modularChart)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.userMarker)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.flag)).BeginInit();
            this.SuspendLayout();
            // 
            // modularChart
            // 
            this.modularChart.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.modularChart.BackColor = System.Drawing.Color.Transparent;
            this.modularChart.BorderlineColor = System.Drawing.Color.Transparent;
            chartArea1.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea1.AxisX.LabelStyle.Enabled = false;
            chartArea1.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea1.AxisX.MajorGrid.Enabled = false;
            chartArea1.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea1.AxisX.MajorTickMark.Enabled = false;
            chartArea1.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea1.AxisX.Maximum = 300D;
            chartArea1.AxisX.Minimum = 0D;
            chartArea1.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea1.AxisX.Title = "Lead III";
            chartArea1.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea1.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea1.AxisY.LabelStyle.Enabled = false;
            chartArea1.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea1.AxisY.LineWidth = 2;
            chartArea1.AxisY.MajorGrid.Enabled = false;
            chartArea1.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea1.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea1.AxisY2.LabelStyle.Enabled = false;
            chartArea1.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea1.AxisY2.LineWidth = 2;
            chartArea1.AxisY2.MajorGrid.Enabled = false;
            chartArea1.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea1.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea1.BackColor = System.Drawing.Color.Transparent;
            chartArea1.BorderColor = System.Drawing.Color.Transparent;
            chartArea1.BorderWidth = 0;
            chartArea1.Name = "ChartArea1";
            chartArea2.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea2.AxisX.LabelStyle.Enabled = false;
            chartArea2.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea2.AxisX.MajorGrid.Enabled = false;
            chartArea2.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea2.AxisX.MajorTickMark.Enabled = false;
            chartArea2.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea2.AxisX.Maximum = 300D;
            chartArea2.AxisX.Minimum = 0D;
            chartArea2.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea2.AxisX.Title = "Lead I";
            chartArea2.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea2.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea2.AxisY.LabelStyle.Enabled = false;
            chartArea2.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea2.AxisY.LineWidth = 2;
            chartArea2.AxisY.MajorGrid.Enabled = false;
            chartArea2.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea2.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea2.AxisY2.LabelStyle.Enabled = false;
            chartArea2.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea2.AxisY2.LineWidth = 2;
            chartArea2.AxisY2.MajorGrid.Enabled = false;
            chartArea2.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea2.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea2.BackColor = System.Drawing.Color.Transparent;
            chartArea2.BorderColor = System.Drawing.Color.Transparent;
            chartArea2.BorderWidth = 0;
            chartArea2.Name = "ChartArea2";
            chartArea3.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea3.AxisX.LabelStyle.Enabled = false;
            chartArea3.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea3.AxisX.MajorGrid.Enabled = false;
            chartArea3.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea3.AxisX.MajorTickMark.Enabled = false;
            chartArea3.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea3.AxisX.Maximum = 300D;
            chartArea3.AxisX.Minimum = 0D;
            chartArea3.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea3.AxisX.Title = "V1";
            chartArea3.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea3.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea3.AxisY.LabelStyle.Enabled = false;
            chartArea3.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea3.AxisY.LineWidth = 2;
            chartArea3.AxisY.MajorGrid.Enabled = false;
            chartArea3.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea3.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea3.AxisY2.LabelStyle.Enabled = false;
            chartArea3.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea3.AxisY2.LineWidth = 2;
            chartArea3.AxisY2.MajorGrid.Enabled = false;
            chartArea3.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea3.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea3.BackColor = System.Drawing.Color.Transparent;
            chartArea3.BorderColor = System.Drawing.Color.Transparent;
            chartArea3.BorderWidth = 0;
            chartArea3.Name = "ChartArea3";
            chartArea4.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea4.AxisX.LabelStyle.Enabled = false;
            chartArea4.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea4.AxisX.MajorGrid.Enabled = false;
            chartArea4.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea4.AxisX.MajorTickMark.Enabled = false;
            chartArea4.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea4.AxisX.Maximum = 300D;
            chartArea4.AxisX.Minimum = 0D;
            chartArea4.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea4.AxisX.Title = "V2";
            chartArea4.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea4.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea4.AxisY.LabelStyle.Enabled = false;
            chartArea4.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea4.AxisY.LineWidth = 2;
            chartArea4.AxisY.MajorGrid.Enabled = false;
            chartArea4.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea4.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea4.AxisY2.LabelStyle.Enabled = false;
            chartArea4.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea4.AxisY2.LineWidth = 2;
            chartArea4.AxisY2.MajorGrid.Enabled = false;
            chartArea4.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea4.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea4.BackColor = System.Drawing.Color.Transparent;
            chartArea4.BorderColor = System.Drawing.Color.Transparent;
            chartArea4.BorderWidth = 0;
            chartArea4.Name = "ChartArea4";
            chartArea5.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea5.AxisX.LabelStyle.Enabled = false;
            chartArea5.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea5.AxisX.MajorGrid.Enabled = false;
            chartArea5.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea5.AxisX.MajorTickMark.Enabled = false;
            chartArea5.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea5.AxisX.Maximum = 300D;
            chartArea5.AxisX.Minimum = 0D;
            chartArea5.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea5.AxisX.Title = "V3";
            chartArea5.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea5.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea5.AxisY.LabelStyle.Enabled = false;
            chartArea5.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea5.AxisY.LineWidth = 2;
            chartArea5.AxisY.MajorGrid.Enabled = false;
            chartArea5.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea5.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea5.AxisY2.LabelStyle.Enabled = false;
            chartArea5.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea5.AxisY2.LineWidth = 2;
            chartArea5.AxisY2.MajorGrid.Enabled = false;
            chartArea5.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea5.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea5.BackColor = System.Drawing.Color.Transparent;
            chartArea5.BorderColor = System.Drawing.Color.Transparent;
            chartArea5.BorderWidth = 0;
            chartArea5.Name = "ChartArea5";
            chartArea6.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea6.AxisX.LabelStyle.Enabled = false;
            chartArea6.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea6.AxisX.MajorGrid.Enabled = false;
            chartArea6.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea6.AxisX.MajorTickMark.Enabled = false;
            chartArea6.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea6.AxisX.Maximum = 300D;
            chartArea6.AxisX.Minimum = 0D;
            chartArea6.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea6.AxisX.Title = "V4";
            chartArea6.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea6.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea6.AxisY.LabelStyle.Enabled = false;
            chartArea6.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea6.AxisY.LineWidth = 2;
            chartArea6.AxisY.MajorGrid.Enabled = false;
            chartArea6.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea6.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea6.AxisY2.LabelStyle.Enabled = false;
            chartArea6.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea6.AxisY2.LineWidth = 2;
            chartArea6.AxisY2.MajorGrid.Enabled = false;
            chartArea6.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea6.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea6.BackColor = System.Drawing.Color.Transparent;
            chartArea6.BorderColor = System.Drawing.Color.Transparent;
            chartArea6.BorderWidth = 0;
            chartArea6.Name = "ChartArea6";
            chartArea7.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea7.AxisX.LabelStyle.Enabled = false;
            chartArea7.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea7.AxisX.MajorGrid.Enabled = false;
            chartArea7.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea7.AxisX.MajorTickMark.Enabled = false;
            chartArea7.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea7.AxisX.Maximum = 300D;
            chartArea7.AxisX.Minimum = 0D;
            chartArea7.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea7.AxisX.Title = "V5";
            chartArea7.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea7.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea7.AxisY.LabelStyle.Enabled = false;
            chartArea7.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea7.AxisY.LineWidth = 2;
            chartArea7.AxisY.MajorGrid.Enabled = false;
            chartArea7.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea7.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea7.AxisY2.LabelStyle.Enabled = false;
            chartArea7.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea7.AxisY2.LineWidth = 2;
            chartArea7.AxisY2.MajorGrid.Enabled = false;
            chartArea7.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea7.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea7.BackColor = System.Drawing.Color.Transparent;
            chartArea7.BorderColor = System.Drawing.Color.Transparent;
            chartArea7.BorderWidth = 0;
            chartArea7.Name = "ChartArea7";
            chartArea8.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea8.AxisX.LabelStyle.Enabled = false;
            chartArea8.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea8.AxisX.MajorGrid.Enabled = false;
            chartArea8.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea8.AxisX.MajorTickMark.Enabled = false;
            chartArea8.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea8.AxisX.Maximum = 300D;
            chartArea8.AxisX.Minimum = 0D;
            chartArea8.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea8.AxisX.Title = "V6";
            chartArea8.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea8.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea8.AxisY.LabelStyle.Enabled = false;
            chartArea8.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea8.AxisY.LineWidth = 2;
            chartArea8.AxisY.MajorGrid.Enabled = false;
            chartArea8.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea8.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea8.AxisY2.LabelStyle.Enabled = false;
            chartArea8.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea8.AxisY2.LineWidth = 2;
            chartArea8.AxisY2.MajorGrid.Enabled = false;
            chartArea8.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea8.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea8.BackColor = System.Drawing.Color.Transparent;
            chartArea8.BorderColor = System.Drawing.Color.Transparent;
            chartArea8.BorderWidth = 0;
            chartArea8.Name = "ChartArea8";
            chartArea9.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea9.AxisX.LabelStyle.Enabled = false;
            chartArea9.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea9.AxisX.MajorGrid.Enabled = false;
            chartArea9.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea9.AxisX.MajorTickMark.Enabled = false;
            chartArea9.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea9.AxisX.Maximum = 300D;
            chartArea9.AxisX.Minimum = 0D;
            chartArea9.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea9.AxisX.Title = "Lead II";
            chartArea9.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea9.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea9.AxisY.LabelStyle.Enabled = false;
            chartArea9.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea9.AxisY.LineWidth = 2;
            chartArea9.AxisY.MajorGrid.Enabled = false;
            chartArea9.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea9.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea9.AxisY2.LabelStyle.Enabled = false;
            chartArea9.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea9.AxisY2.LineWidth = 2;
            chartArea9.AxisY2.MajorGrid.Enabled = false;
            chartArea9.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea9.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea9.BackColor = System.Drawing.Color.Transparent;
            chartArea9.BorderColor = System.Drawing.Color.Transparent;
            chartArea9.BorderWidth = 0;
            chartArea9.Name = "ChartArea9";
            chartArea10.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea10.AxisX.LabelStyle.Enabled = false;
            chartArea10.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea10.AxisX.MajorGrid.Enabled = false;
            chartArea10.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea10.AxisX.MajorTickMark.Enabled = false;
            chartArea10.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea10.AxisX.Maximum = 300D;
            chartArea10.AxisX.Minimum = 0D;
            chartArea10.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea10.AxisX.Title = "aVL";
            chartArea10.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea10.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea10.AxisY.LabelStyle.Enabled = false;
            chartArea10.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea10.AxisY.LineWidth = 2;
            chartArea10.AxisY.MajorGrid.Enabled = false;
            chartArea10.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea10.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea10.AxisY2.LabelStyle.Enabled = false;
            chartArea10.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea10.AxisY2.LineWidth = 2;
            chartArea10.AxisY2.MajorGrid.Enabled = false;
            chartArea10.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea10.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea10.BackColor = System.Drawing.Color.Transparent;
            chartArea10.BorderColor = System.Drawing.Color.Transparent;
            chartArea10.BorderWidth = 0;
            chartArea10.Name = "ChartArea10";
            chartArea11.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea11.AxisX.LabelStyle.Enabled = false;
            chartArea11.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea11.AxisX.MajorGrid.Enabled = false;
            chartArea11.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea11.AxisX.MajorTickMark.Enabled = false;
            chartArea11.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea11.AxisX.Maximum = 300D;
            chartArea11.AxisX.Minimum = 0D;
            chartArea11.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea11.AxisX.Title = "aVF";
            chartArea11.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea11.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea11.AxisY.LabelStyle.Enabled = false;
            chartArea11.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea11.AxisY.LineWidth = 2;
            chartArea11.AxisY.MajorGrid.Enabled = false;
            chartArea11.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea11.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea11.AxisY2.LabelStyle.Enabled = false;
            chartArea11.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea11.AxisY2.LineWidth = 2;
            chartArea11.AxisY2.MajorGrid.Enabled = false;
            chartArea11.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea11.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea11.BackColor = System.Drawing.Color.Transparent;
            chartArea11.BorderColor = System.Drawing.Color.Transparent;
            chartArea11.BorderWidth = 0;
            chartArea11.Name = "ChartArea11";
            chartArea12.AxisX.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea12.AxisX.LabelStyle.Enabled = false;
            chartArea12.AxisX.LineColor = System.Drawing.Color.Transparent;
            chartArea12.AxisX.MajorGrid.Enabled = false;
            chartArea12.AxisX.MajorGrid.LineColor = System.Drawing.Color.White;
            chartArea12.AxisX.MajorTickMark.Enabled = false;
            chartArea12.AxisX.MajorTickMark.LineColor = System.Drawing.Color.White;
            chartArea12.AxisX.Maximum = 300D;
            chartArea12.AxisX.Minimum = 0D;
            chartArea12.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea12.AxisX.Title = "aV";
            chartArea12.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea12.AxisY.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea12.AxisY.LabelStyle.Enabled = false;
            chartArea12.AxisY.LineColor = System.Drawing.Color.Silver;
            chartArea12.AxisY.LineWidth = 2;
            chartArea12.AxisY.MajorGrid.Enabled = false;
            chartArea12.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea12.AxisY2.Enabled = System.Windows.Forms.DataVisualization.Charting.AxisEnabled.True;
            chartArea12.AxisY2.LabelStyle.Enabled = false;
            chartArea12.AxisY2.LineColor = System.Drawing.Color.Silver;
            chartArea12.AxisY2.LineWidth = 2;
            chartArea12.AxisY2.MajorGrid.Enabled = false;
            chartArea12.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Silver;
            chartArea12.AxisY2.MajorTickMark.LineColor = System.Drawing.Color.Silver;
            chartArea12.BackColor = System.Drawing.Color.Transparent;
            chartArea12.BorderColor = System.Drawing.Color.Transparent;
            chartArea12.BorderWidth = 0;
            chartArea12.Name = "ChartArea12";
            this.modularChart.ChartAreas.Add(chartArea1);
            this.modularChart.ChartAreas.Add(chartArea2);
            this.modularChart.ChartAreas.Add(chartArea3);
            this.modularChart.ChartAreas.Add(chartArea4);
            this.modularChart.ChartAreas.Add(chartArea5);
            this.modularChart.ChartAreas.Add(chartArea6);
            this.modularChart.ChartAreas.Add(chartArea7);
            this.modularChart.ChartAreas.Add(chartArea8);
            this.modularChart.ChartAreas.Add(chartArea9);
            this.modularChart.ChartAreas.Add(chartArea10);
            this.modularChart.ChartAreas.Add(chartArea11);
            this.modularChart.ChartAreas.Add(chartArea12);
            this.modularChart.Location = new System.Drawing.Point(0, 0);
            this.modularChart.Margin = new System.Windows.Forms.Padding(0);
            this.modularChart.Name = "modularChart";
            series1.BorderColor = System.Drawing.Color.Red;
            series1.BorderWidth = 2;
            series1.ChartArea = "ChartArea1";
            series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series1.Color = System.Drawing.Color.Red;
            series1.Name = "Series1";
            series1.SmartLabelStyle.Enabled = false;
            series2.BorderColor = System.Drawing.Color.Red;
            series2.BorderWidth = 2;
            series2.ChartArea = "ChartArea1";
            series2.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series2.Color = System.Drawing.Color.Red;
            series2.Name = "series2";
            series2.SmartLabelStyle.Enabled = false;
            series3.BorderColor = System.Drawing.Color.Green;
            series3.BorderWidth = 2;
            series3.ChartArea = "ChartArea2";
            series3.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series3.Color = System.Drawing.Color.Green;
            series3.Name = "series3";
            series3.SmartLabelStyle.Enabled = false;
            series4.BorderColor = System.Drawing.Color.Green;
            series4.BorderWidth = 2;
            series4.ChartArea = "ChartArea2";
            series4.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series4.Color = System.Drawing.Color.Green;
            series4.Name = "Series4";
            series4.SmartLabelStyle.Enabled = false;
            series5.BorderColor = System.Drawing.Color.DodgerBlue;
            series5.BorderWidth = 2;
            series5.ChartArea = "ChartArea3";
            series5.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series5.Color = System.Drawing.Color.DodgerBlue;
            series5.Name = "series5";
            series5.SmartLabelStyle.Enabled = false;
            series6.BorderColor = System.Drawing.Color.DodgerBlue;
            series6.BorderWidth = 2;
            series6.ChartArea = "ChartArea3";
            series6.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series6.Color = System.Drawing.Color.DodgerBlue;
            series6.Name = "series6";
            series6.SmartLabelStyle.Enabled = false;
            series7.BorderColor = System.Drawing.Color.Cyan;
            series7.BorderWidth = 2;
            series7.ChartArea = "ChartArea4";
            series7.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series7.Color = System.Drawing.Color.Cyan;
            series7.Name = "Series7";
            series7.SmartLabelStyle.Enabled = false;
            series8.BorderColor = System.Drawing.Color.Cyan;
            series8.BorderWidth = 2;
            series8.ChartArea = "ChartArea4";
            series8.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series8.Color = System.Drawing.Color.Cyan;
            series8.Name = "series8";
            series8.SmartLabelStyle.Enabled = false;
            series9.BorderColor = System.Drawing.Color.Honeydew;
            series9.BorderWidth = 2;
            series9.ChartArea = "ChartArea5";
            series9.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series9.Color = System.Drawing.Color.Honeydew;
            series9.Name = "series9";
            series9.SmartLabelStyle.Enabled = false;
            series10.BorderColor = System.Drawing.Color.Honeydew;
            series10.BorderWidth = 2;
            series10.ChartArea = "ChartArea5";
            series10.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series10.Color = System.Drawing.Color.Honeydew;
            series10.Name = "Series10";
            series10.SmartLabelStyle.Enabled = false;
            series11.BorderColor = System.Drawing.Color.DarkGray;
            series11.BorderWidth = 2;
            series11.ChartArea = "ChartArea6";
            series11.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series11.Color = System.Drawing.Color.DarkGray;
            series11.Name = "Series11";
            series11.SmartLabelStyle.Enabled = false;
            series12.BorderColor = System.Drawing.Color.DarkGray;
            series12.BorderWidth = 2;
            series12.ChartArea = "ChartArea6";
            series12.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series12.Color = System.Drawing.Color.DarkGray;
            series12.Name = "series12";
            series12.SmartLabelStyle.Enabled = false;
            series13.BorderColor = System.Drawing.Color.HotPink;
            series13.BorderWidth = 2;
            series13.ChartArea = "ChartArea7";
            series13.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series13.Color = System.Drawing.Color.HotPink;
            series13.Name = "series13";
            series13.SmartLabelStyle.Enabled = false;
            series14.BorderColor = System.Drawing.Color.HotPink;
            series14.BorderWidth = 2;
            series14.ChartArea = "ChartArea7";
            series14.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series14.Color = System.Drawing.Color.HotPink;
            series14.Name = "Series14";
            series14.SmartLabelStyle.Enabled = false;
            series15.BorderColor = System.Drawing.Color.Yellow;
            series15.BorderWidth = 2;
            series15.ChartArea = "ChartArea8";
            series15.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series15.Color = System.Drawing.Color.Yellow;
            series15.Name = "series15";
            series15.SmartLabelStyle.Enabled = false;
            series16.BorderColor = System.Drawing.Color.Yellow;
            series16.BorderWidth = 2;
            series16.ChartArea = "ChartArea8";
            series16.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series16.Color = System.Drawing.Color.Yellow;
            series16.Name = "series16";
            series16.SmartLabelStyle.Enabled = false;
            series17.BorderColor = System.Drawing.Color.SkyBlue;
            series17.BorderWidth = 2;
            series17.ChartArea = "ChartArea9";
            series17.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series17.Color = System.Drawing.Color.SkyBlue;
            series17.Name = "Series17";
            series17.SmartLabelStyle.Enabled = false;
            series18.BorderColor = System.Drawing.Color.SkyBlue;
            series18.BorderWidth = 2;
            series18.ChartArea = "ChartArea9";
            series18.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series18.Color = System.Drawing.Color.SkyBlue;
            series18.Name = "series18";
            series18.SmartLabelStyle.Enabled = false;
            series19.BorderColor = System.Drawing.Color.Khaki;
            series19.BorderWidth = 2;
            series19.ChartArea = "ChartArea10";
            series19.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series19.Color = System.Drawing.Color.Khaki;
            series19.Name = "series19";
            series19.SmartLabelStyle.Enabled = false;
            series20.BorderColor = System.Drawing.Color.Khaki;
            series20.BorderWidth = 2;
            series20.ChartArea = "ChartArea10";
            series20.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series20.Color = System.Drawing.Color.Khaki;
            series20.Name = "Series20";
            series20.SmartLabelStyle.Enabled = false;
            series21.BorderColor = System.Drawing.Color.CadetBlue;
            series21.BorderWidth = 2;
            series21.ChartArea = "ChartArea11";
            series21.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series21.Color = System.Drawing.Color.CadetBlue;
            series21.Name = "Series21";
            series21.SmartLabelStyle.Enabled = false;
            series22.BorderColor = System.Drawing.Color.CadetBlue;
            series22.BorderWidth = 2;
            series22.ChartArea = "ChartArea11";
            series22.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series22.Color = System.Drawing.Color.CadetBlue;
            series22.Name = "Series22";
            series22.SmartLabelStyle.Enabled = false;
            series23.BorderColor = System.Drawing.Color.Tomato;
            series23.BorderWidth = 2;
            series23.ChartArea = "ChartArea12";
            series23.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series23.Color = System.Drawing.Color.Tomato;
            series23.Name = "Series23";
            series23.SmartLabelStyle.Enabled = false;
            series24.BorderColor = System.Drawing.Color.Tomato;
            series24.BorderWidth = 2;
            series24.ChartArea = "ChartArea12";
            series24.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.FastLine;
            series24.Color = System.Drawing.Color.Tomato;
            series24.Name = "Series24";
            series24.SmartLabelStyle.Enabled = false;
            this.modularChart.Series.Add(series1);
            this.modularChart.Series.Add(series2);
            this.modularChart.Series.Add(series3);
            this.modularChart.Series.Add(series4);
            this.modularChart.Series.Add(series5);
            this.modularChart.Series.Add(series6);
            this.modularChart.Series.Add(series7);
            this.modularChart.Series.Add(series8);
            this.modularChart.Series.Add(series9);
            this.modularChart.Series.Add(series10);
            this.modularChart.Series.Add(series11);
            this.modularChart.Series.Add(series12);
            this.modularChart.Series.Add(series13);
            this.modularChart.Series.Add(series14);
            this.modularChart.Series.Add(series15);
            this.modularChart.Series.Add(series16);
            this.modularChart.Series.Add(series17);
            this.modularChart.Series.Add(series18);
            this.modularChart.Series.Add(series19);
            this.modularChart.Series.Add(series20);
            this.modularChart.Series.Add(series21);
            this.modularChart.Series.Add(series22);
            this.modularChart.Series.Add(series23);
            this.modularChart.Series.Add(series24);
            this.modularChart.Size = new System.Drawing.Size(265, 260);
            this.modularChart.TabIndex = 0;
            this.modularChart.Text = "chart1";
            // 
            // userMarker
            // 
            this.userMarker.BackColor = System.Drawing.Color.Red;
            this.userMarker.BackgroundImage = global::CardioLeaf.Properties.Resources.evBg;
            this.userMarker.ErrorImage = null;
            this.userMarker.InitialImage = null;
            this.userMarker.Location = new System.Drawing.Point(150, 20);
            this.userMarker.Name = "userMarker";
            this.userMarker.Size = new System.Drawing.Size(2, 650);
            this.userMarker.TabIndex = 1;
            this.userMarker.TabStop = false;
            this.userMarker.Visible = false;
            // 
            // flag
            // 
            this.flag.BackColor = System.Drawing.Color.Transparent;
            this.flag.BackgroundImage = global::CardioLeaf.Properties.Resources.flag_red;
            this.flag.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.flag.ErrorImage = null;
            this.flag.InitialImage = null;
            this.flag.Location = new System.Drawing.Point(150, 0);
            this.flag.Name = "flag";
            this.flag.Size = new System.Drawing.Size(14, 19);
            this.flag.TabIndex = 2;
            this.flag.TabStop = false;
            this.flag.Visible = false;
            // 
            // scaleLabel
            // 
            this.scaleLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.scaleLabel.AutoSize = true;
            this.scaleLabel.BackColor = System.Drawing.Color.Transparent;
            this.scaleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.scaleLabel.ForeColor = System.Drawing.Color.Transparent;
            this.scaleLabel.Location = new System.Drawing.Point(159, 237);
            this.scaleLabel.Name = "scaleLabel";
            this.scaleLabel.Size = new System.Drawing.Size(130, 12);
            this.scaleLabel.TabIndex = 3;
            this.scaleLabel.Text = "Scale : 1mV per Division";
            this.scaleLabel.TextAlign = System.Drawing.ContentAlignment.BottomRight;
            this.scaleLabel.Visible = false;
            // 
            // ChartControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Controls.Add(this.scaleLabel);
            this.Controls.Add(this.flag);
            this.Controls.Add(this.userMarker);
            this.Controls.Add(this.modularChart);
            this.Name = "ChartControl";
            this.Size = new System.Drawing.Size(300, 300);
            ((System.ComponentModel.ISupportInitialize)(this.modularChart)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.userMarker)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.flag)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.DataVisualization.Charting.Chart modularChart;
        public System.Windows.Forms.PictureBox userMarker;
        public System.Windows.Forms.PictureBox flag;
        private System.Windows.Forms.Label scaleLabel;

    }
}
